<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ManualpracticeSampleApiLib\Models\GetcodeResponse;

/**
 * Builder for model GetcodeResponse
 *
 * @see GetcodeResponse
 */
class GetcodeResponseBuilder
{
    /**
     * @var GetcodeResponse
     */
    private $instance;

    private function __construct(GetcodeResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Getcode Response Builder object.
     */
    public static function init(): self
    {
        return new self(new GetcodeResponse());
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Getcode Response object.
     */
    public function build(): GetcodeResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
