<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ManualpracticeSampleApiLib\Models\MultiplnumbersResponse;

/**
 * Builder for model MultiplnumbersResponse
 *
 * @see MultiplnumbersResponse
 */
class MultiplnumbersResponseBuilder
{
    /**
     * @var MultiplnumbersResponse
     */
    private $instance;

    private function __construct(MultiplnumbersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Multiplnumbers Response Builder object.
     */
    public static function init(): self
    {
        return new self(new MultiplnumbersResponse());
    }

    /**
     * Sets result field.
     *
     * @param float|null $value
     */
    public function result(?float $value): self
    {
        $this->instance->setResult($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Multiplnumbers Response object.
     */
    public function build(): MultiplnumbersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
