<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Models\Builders;

use Core\Utils\CoreHelper;
use ManualpracticeSampleApiLib\Models\UpdatenumberResponse;

/**
 * Builder for model UpdatenumberResponse
 *
 * @see UpdatenumberResponse
 */
class UpdatenumberResponseBuilder
{
    /**
     * @var UpdatenumberResponse
     */
    private $instance;

    private function __construct(UpdatenumberResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Updatenumber Response Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdatenumberResponse());
    }

    /**
     * Sets result field.
     *
     * @param string|null $value
     */
    public function result(?string $value): self
    {
        $this->instance->setResult($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Updatenumber Response object.
     */
    public function build(): UpdatenumberResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
