<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Apis;

use Core\Request\Parameters\QueryParam;
use CoreInterfaces\Core\Request\RequestMethod;
use ManualpracticeSampleApiLib\Http\ApiResponse;
use ManualpracticeSampleApiLib\Models\AddnumbersResponse;

class AddnumbermathApi extends BaseApi
{
    /**
     * @param float $num1
     * @param float $num2
     *
     * @return ApiResponse Response from the API call
     */
    public function addNumbers(float $num1, float $num2): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/addnumbers')
            ->auth('acgauth2')
            ->parameters(QueryParam::init('num1', $num1)->required(), QueryParam::init('num2', $num2)->required());

        $_resHandler = $this->responseHandler()->type(AddnumbersResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
