<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Apis;

use CoreInterfaces\Core\Request\RequestMethod;
use ManualpracticeSampleApiLib\Http\ApiResponse;
use ManualpracticeSampleApiLib\Models\GetcodeResponse;

class Api extends BaseApi
{
    /**
     * @return ApiResponse Response from the API call
     */
    public function testEndpoint(): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/getcode')->auth('acgauth2');

        $_resHandler = $this->responseHandler()->type(GetcodeResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
