<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Apis;

use Core\Request\Parameters\FormParam;
use Core\Request\Parameters\HeaderParam;
use CoreInterfaces\Core\Request\RequestMethod;
use ManualpracticeSampleApiLib\Http\ApiResponse;
use ManualpracticeSampleApiLib\Models\CreatesquarerootResponse;

class CreatesquarerootmathApi extends BaseApi
{
    /**
     * @param float|null $number
     *
     * @return ApiResponse Response from the API call
     */
    public function createSquareRoot(?float $number = null): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/createsquareroot')
            ->auth('acgauth2')
            ->parameters(
                HeaderParam::init('Content-Type', 'application/x-www-form-urlencoded'),
                FormParam::init('number', $number)
            );

        $_resHandler = $this->responseHandler()->type(CreatesquarerootResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
