<?php

declare(strict_types=1);

/*
 * ManualpracticeSampleApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ManualpracticeSampleApiLib\Apis;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use CoreInterfaces\Core\Request\RequestMethod;
use ManualpracticeSampleApiLib\Http\ApiResponse;
use ManualpracticeSampleApiLib\Models\Complexvalueset;
use ManualpracticeSampleApiLib\Models\UpdatenumberResponse;

class UpdatenumbermathApi extends BaseApi
{
    /**
     * @param int $body
     *
     * @return ApiResponse Response from the API call
     */
    public function updateNumber(int $body): ApiResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::PUT, '/updatenumber')
            ->auth('acgauth2')
            ->parameters(
                HeaderParam::init('Content-Type', 'application/json'),
                BodyParam::init($body)->required()->serializeBy([Complexvalueset::class, 'checkValue'])
            );

        $_resHandler = $this->responseHandler()->type(UpdatenumberResponse::class)->returnApiResponse();

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
